# Generated by Django 5.2.2 on 2025-06-10 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JewelryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_line_no', models.CharField(blank=True, max_length=50, null=True)),
                ('model_code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('model_number', models.CharField(max_length=100)),
                ('gold_karat', models.CharField(max_length=10)),
                ('gold_color', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('total_metal_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_usd', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Diamond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('total_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('jewelry_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diamonds', to='product.jewelryproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ColoredStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('total_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('jewelry_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colored_stones', to='product.jewelryproduct')),
            ],
        ),
    ]
