# Generated by Django 5.2.2 on 2025-06-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jewelryproduct',
            name='model_code',
        ),
    ]
