# Generated by Django 5.2.2 on 2025-06-11 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_jewelryproduct_model_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='JewelryProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='jewelry_photos/')),
                ('alt_text', models.CharField(blank=True, max_length=100, null=True)),
                ('jewelry_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.jewelryproduct')),
            ],
        ),
    ]
